version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar ./main-app-master-degree-all.jar
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/kotlin-app
      - DB_USERNAME=postgres
      - DB_PASSWORD=Tolstochok3000
      - DB_SCHEMA=public
      - KAFKA_URL=kafka/9092
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "kotlin-app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Tolstochok3000"

    ports:
      - "5432:5432"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafka-network
networks:
  kafka-network:
    ipam:
      config:
        - subnet: 172.25.1.0/16

